# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Bán hàng',
    'version': '1.0',
    'sequence': 0,
    'summary': 'Quản lý bán hàng',
    'depends': [
        'danh_muc',        
        'account_ex',
        'stock_ex',
        'purchase_ex',
    ],
    'data': [
		# 'views/sale_ex_hop_dong_ban_de_nghi_ghi_doanh_so_form_view.xml',
		'views/sale_ex_hop_dong_ban_chon_chung_tu_thu_form_view.xml',
		'views/sale_ex_hop_dong_ban_chon_chung_tu_chi_form_view.xml',
		# 'templates/sale_ex_hop_dong_ban_template.xml',
		'views/sale_ex_hop_dong_ban_view.xml',
        'views/sale_ex_bu_tru_cong_no_view.xml',
		'views/sale_ex_bo_doi_tru_view.xml',
		'views/sale_ex_doi_tru_chung_tu_nhieu_doi_tuong_view.xml',
		'views/sale_ex_tinh_gia_ban_view.xml',
		
		
		# 'templates/sale_ex_bao_gia_template.xml',
		'views/sale_ex_bao_gia_view.xml',
		# 'views/sale_ex_phan_bo_chiet_khau_theo_tong_gia_tri_hd_chi_tiet_view.xml',
		'views/sale_ex_phan_bo_chiet_khau_theo_tong_gia_tri_hd_form_view.xml',
		'templates/sale_ex_giam_gia_hang_ban_template.xml',
        # 'templates/sale_ex_giam_gia_hang_ban_02_tt_phieuchi_template.xml',
        # 'templates/sale_ex_giam_gia_hang_ban_02_tt_phieuchi_a5_template.xml',
        # 'templates/sale_ex_giam_gia_hang_ban_02_tt_phieuchi_2_lien_template.xml',
		# 'templates/sale_ex_giam_gia_hang_ban_chungtuketoan_template.xml',
		# 'templates/sale_ex_tra_lai_hang_ban_ctkt_template.xml',
        'templates/sale_ex_tra_lai_hang_ban_01_vt_phieu_nhap_kho_template.xml',
        'templates/sale_ex_tra_lai_hang_ban_01_vt_phieu_nhap_kho_a5_template.xml',
        # 'templates/sale_ex_tra_lai_hang_ban_02_tt_phieu_chi_template.xml',
        # 'templates/sale_ex_tra_lai_hang_ban_02_tt_phieu_chi_2_lien_template.xml',
        # 'templates/sale_ex_tra_lai_hang_ban_02_tt_phieu_chi_a5_template.xml',
        'views/sale_ex_tra_lai_hang_ban_view.xml',
		'views/sale_ex_thu_tien_khach_hang_view.xml',
		'views/sale_ex_doi_tru_chung_tu_view.xml',
		'views/sale_ex_hoa_don_ban_hang_view.xml',
		'views/sale_ex_giam_gia_hang_ban_view.xml',
		'views/sale_ex_chung_tu_ban_hang_view.xml',
		'views/sale_ex_chung_tu_ban_hang_chi_tiet_view.xml',
        # 'views/sale_ex_hoa_don_dien_tu_view.xml',
        # 'templates/sale_ex_01_tt_phieu_thu_template.xml',
        # 'templates/sale_ex_02_vt_phieu_xuat_kho_template.xml',
        # 'templates/sale_ex_phieu_xuat_kho_ban_hang_template.xml',
        'templates/sale_ex_templates.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': [],
}
