# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Tiền lương',
    'version': '1.0',
    'sequence': 0,
    'summary': 'Module mẫu',
    'depends': [
    	'danh_muc',
    	'account_ex',
    ],
    'data': [
		'templates/tien_luong_tinh_luong_bang_tt_tien_luong_luong_co_dinh_A4_template.xml',
		'templates/tien_luong_tinh_luong_bang_tt_tien_luong_luong_thoi_gian_theo_buoi_A4_template.xml',
		'templates/tien_luong_tinh_luong_bang_tt_tien_luong_luong_thoi_gian_theo_gio_A4_template.xml',
		'templates/tien_luong_tinh_luong_bang_luong_tam_ung_template.xml',
		'templates/tien_luong_bang_cham_cong_lam_them_gio_template.xml',
		'templates/tien_luong_bang_cham_cong_template.xml',
		'views/tien_luong_quy_dinh_luong_bao_hiem_thue_tncn_view.xml',
		'views/tien_luong_nop_bao_hiem_form_tham_so_view.xml',
		'templates/tien_luong_hach_toan_chi_phi_luong_template.xml',
		'views/tien_luong_hach_toan_chi_phi_luong_form_tham_so_view.xml',
		'views/tien_luong_hach_toan_chi_phi_luong_view.xml',
		# 'views/tien_luong_phieu_chi_tra_luong_nhan_vien_view.xml',
		# 'views/tien_luong_uy_nhiem_chi_tra_luong_nhan_vien_view.xml',
		'views/tien_luong_tra_luong_form_tham_so_view.xml',
		'views/tien_luong_bang_luong_form_tham_so_view.xml',
		# 'views/tien_luong_bang_luong_chi_tiet_view.xml',
		'views/tien_luong_bang_luong_view.xml',
		'views/tien_luong_bang_tong_hop_cham_cong_view.xml',
		# 'views/tien_luong_bang_tong_hop_cham_cong_chi_tiet_view.xml',
		'views/tien_luong_tong_hop_cham_cong_tham_so_view.xml',
		'views/tien_luong_bang_cham_cong_chi_tiet_master_view.xml',
		# 'views/tien_luong_bang_cham_cong_chi_tiet_detail_view.xml',
		'views/tien_luong_bang_cham_cong_form_view.xml',
		'views/tien_luong_lich_su_tra_luong_view.xml',
		'views/tien_luong_tra_luong_nhan_vien_view.xml',
		'views/tien_luong_nop_tien_bao_hiem_view.xml',
		'templates/tien_luong_templates.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': [],
}
