# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
from . import bao_cao_tham_so
from . import bao_cao_nhom_vthh
from . import bao_cao_so_chi_tiet_vat_lieu_cong_cu
from . import bao_cao_bao_cao_tien_do_san_xuat
from . import bao_cao_the_kho
from . import bao_cao_loai_ccdc
from . import bao_cao_so_theo_doi_cong_cu_dung_cu
from . import bao_cao_so_tien_gui_ngan_hang
from . import bao_cao_bang_ke_so_du_ngan_hang
from . import bao_cao_tai_san_co_dinh
from . import bao_cao_so_tai_san_co_dinh
from . import bao_cao_bang_ke_thu_mua_hang
from . import bao_cao_so_chi_tiet_mua_hang
from . import bao_cao_tong_hop_cong_no_phai_tra
from . import bao_cao_chi_tiet_cong_no_phai_tra_nha_cung_cap
from . import bao_cao_so_chi_tiet_ban_hang
from . import bao_cao_s35_dn_so_chi_tiet_ban_hang
from . import bao_cao_tong_hop_cong_no_phai_thu_khach_hang
from . import bao_cao_phan_tich_cong_no_phai_tra_theo_tuoi_no
from . import bao_cao_bien_ban_doi_chieu_va_xac_nhan_cong_no_phai_tra
from . import bao_cao_so_nhat_ky_chung
from . import bao_cao_so_31_dn_so_chi_tiet_thanh_toan_nguoi_mua_hoac_nguoi_ban
from . import bao_cao_s34_dn
from . import bao_cao_so_chi_tiet_tai_khoan_theo_doi_tuong
from . import bao_cao_so_chi_tiet_tai_khoan_theo_doi_tuong_tap_hop_chi_phi_va_khoan_muc_chi_phi
from . import bao_cao_so_quy_tien_mat
from . import bao_cao_tong_hop_ton_kho_theo_lo
from . import bao_cao_chi_tiet_cong_no_phai_thu_khach_hang
from . import bao_cao_phan_tich_cong_no_phai_thu_theo_tuoi_no
from . import bao_cao_tong_hop_lai_lo_theo_don_hang
from . import bao_cao_phan_tich_so_luong_ban_va_doanh_so_theo_nam
from . import bao_cao_bao_cao_so_sanh_so_luong_ban_va_doanh_so_theo_ky
from . import bao_cao_so_ke_toan_chi_tiet_quy_tien_mat
# from . import bao_cao_s36_dn_so_chi_phi_san_xuat_va_kinh_doanh
# from . import bao_cao_s37_dn_the_tinh_gia_thanh_san_pham_dich_vu
from . import bao_cao_bang_tinh_gia_thanh
from . import bao_cao_s03a1_dn_so_nhat_ky_thu_tien
from . import bao_cao_s03_a2_dn_so_nhat_ky_chi_tien
from . import bao_cao_so_chi_tiet_cac_tai_khoan
from . import bao_cao_so3b_dn_so_cai_hinh_thuc_nhat_ky_chung
from . import bao_cao_s02_c1_dn_so_cai_hinh_thuc_chung_tu_ghi_so
from . import bao_cao_s02b_dn_so_dang_ky_chung_tu_ghi_so
from . import bao_cao_s01_dn_nhat_ky_so_cai
# from . import bao_cao_so35dn_so_cai_hinh_thuc_nhat_ky_chung
from . import bao_cao_tong_hop_ton_kho
from . import bao_cao_s10_dn_so_chi_tiet_vat_lieu_cong_cu
from . import bao_cao_tong_hop_mua_hang
from . import bao_cao_so_chi_tiet_vat_tu_hang_hoa
from . import bao_cao_s21_dn_so_tai_san_co_dinh
from . import bao_cao_tong_hop_ban_hang
from . import bao_cao_bang_tong_hop_quyet_toan_thue_gtgt_nam
from . import bao_cao_bang_ke_hoa_don_chung_tu_mua_vao
from . import bao_cao_bang_tong_hop_thanh_toan_tien_luong_bang_luong_co_dinh
from . import bao_cao_bang_tong_hop_thanh_toan_tien_luong_bang_luong_thoi_gian
from . import bao_cao_tong_hop_luong_nhan_vien
from . import bao_cao_thong_bao_cong_no
from . import bao_cao_bang_can_doi_tai_khoan
from . import bao_cao_b01dn_bang_can_doi_ke_toan
from . import bao_cao_tinh_hinh_thuc_hien_don_dat_hang
from . import bao_cao_bang_ke_hoa_don_chung_tu_ban_ra
from . import bao_cao_tong_hop_cong_no_nhan_vien
from . import bao_cao_f01dnn_bang_can_doi_tai_khoan
from . import bao_cao_b02dn_bao_cao_ket_qua_hoat_dong_kinh_doanh
from . import bao_cao_b03dn_bao_cao_luu_chuyen_tien_te_pp_truc_tiep
from . import bao_cao_b03dn_gt_bao_cao_luu_chuyen_tien_te_pp_gian_tiep
from . import bao_cao_tuy_chon_in
from . import bao_cao_02_vt_phieu_xuat_kho
# from . import bao_cao_s37_dn_the_tinh_gia_thanh_san_pham_dich_vu_chi_tiet
from . import bao_cao_01_vt_phieu_nhap_kho
from . import bao_cao_01_vt_phieu_nhap_kho_chi_tiet
from . import bao_cao_phieu_thu_mau_day_du
from . import bao_cao_phieu_thu_mau_day_du_chi_tiet
from . import bao_cao_01_tt_phieu_thu_a5
from . import bao_cao_01_tt_phieu_thu_a5_chi_tiet
from . import bao_cao_01_tt_phieu_thu_mau_2lien
from . import bao_cao_01_tt_phieu_thu_mau_2lien_chi_tiet
from . import bao_cao_01_tt_phieu_thu
from . import bao_cao_01_tt_phieu_thu_chi_tiet
from . import bao_cao_02_tt_phieu_chi
from . import bao_cao_02_tt_phieu_chi_chi_tiet
from . import bao_cao_02_tt_phieu_chi_mau_2lien
from . import bao_cao_02_tt_phieu_chi_mau_2lien_chi_tiet
from . import bao_cao_02_tt_phieu_chi_mau_a5
from . import bao_cao_02_tt_phieu_chi_mau_a5_chi_tiet
from . import bao_cao_phieu_chi_mau_day_du
from . import bao_cao_phieu_chi_mau_day_du_chi_tiet
from . import bao_cao_giay_bao_no
from . import bao_cao_giay_bao_no_chi_tiet
from . import bao_cao_uy_nhiem_chi_shb
from . import bao_cao_uy_nhiem_chi_shb_chi_tiet
from . import bao_cao_uy_nhiem_chi_agribank
from . import bao_cao_uy_nhiem_chi_agribank_chi_tiet
from . import bao_cao_uy_nhiem_chi_mb
from . import bao_cao_uy_nhiem_chi_mb_chi_tiet 
from . import bao_cao_uy_nhiem_chi_techcombank 
from . import bao_cao_uy_nhiem_chi_techcombank_chi_tiet 
from . import bao_cao_uy_nhiem_chi_viettinbank 
from . import bao_cao_uy_nhiem_chi_viettinbank_chi_tiet 
from . import bao_cao_uy_nhiem_chi_bidv 
from . import bao_cao_uy_nhiem_chi_bidv_chi_tiet 
from . import bao_cao_uy_nhiem_chi_pvcombank 
from . import bao_cao_uy_nhiem_chi_pvcombank_chi_tiet 
from . import bao_cao_02_vt_phieu_xuat_kho_chi_tiet 
from . import bao_cao_phieu_xuat_kho_02vt_mau_a5
from . import bao_cao_phieu_xuat_kho_02vt_mau_a5_chi_tiet 
from . import bao_cao_chung_tu_ke_toan 
from . import bao_cao_chung_tu_ke_toan_chi_tiet 
from . import bao_cao_tuy_chinh_tieu_de
from . import ir_actions_report
from . import bao_cao_giay_bao_co
from . import bao_cao_giay_bao_co_chi_tiet
from . import bao_cao_phieu_xuat_kho_ban_hang
from . import bao_cao_phieu_xuat_kho_ban_hang_chi_tiet
from . import bao_cao_don_dat_hang
from . import bao_cao_don_dat_hang_chi_tiet
from . import bao_cao_chung_tu_ghi_tang_tscd
from . import bao_cao_chung_tu_ghi_tang_tscd_bo_phan_cau_thanh
from . import bao_cao_chung_tu_ghi_tang_tscd_nguon_goc_hinh_thanh
from . import bao_cao_chung_tu_ghi_tang_tscd_dung_cu_phu_tung_kem_theo
from . import bao_cao_don_mua_hang
from . import bao_cao_don_mua_hang_chi_tiet
from . import bao_cao_hop_dong_ban_ben_A_ban
from . import bao_cao_hop_dong_ban_ben_A_ban_chi_tiet
from . import bao_cao_bao_gia
from . import bao_cao_bao_gia_chi_tiet
from . import bao_cao_lenh_thao_do
from . import bao_cao_lenh_thao_do_chi_tiet
from . import bao_cao_lenh_lap_rap
from . import bao_cao_lenh_lap_rap_chi_tiet
from . import bao_cao_lenh_san_xuat
from . import bao_cao_lenh_san_xuat_chi_tiet
from . import bao_cao_chi_phi_du_kien_theo_don_dat_hang
from . import bao_cao_don_dat_hang_chi_co_so_luong
from . import bao_cao_don_dat_hang_chi_co_so_luong_chi_tiet
from . import bao_cao_don_dat_hang_bao_gom_nguyen_vat_lieu
from . import bao_cao_don_dat_hang_bao_gom_nguyen_vat_lieu_chi_tiet
from . import bao_cao_dieu_chuyen_ccdc
from . import bao_cao_dieu_chuyen_ccdc_chi_tiet
from . import bao_cao_don_dat_hang_du_kien_chi_phi
from . import bao_cao_don_dat_hang_du_kien_chi_phi_chi_tiet
from . import bao_cao_hop_dong_ban_ben_A_mua
from . import bao_cao_hop_dong_ban_ben_A_mua_chi_tiet
from . import bao_cao_gia_thanh_tong_hop_chi_phi_sxkd
from . import bao_cao_gia_thanh_so_chi_tiet_tai_khoan_chi_phi_san_xuat
from . import bao_cao_chung_tu_ghi_giam_ccdc
from . import bao_cao_chung_tu_ghi_giam_ccdc_chi_tiet
from . import bao_cao_bien_ban_kiem_ke
from . import bao_cao_bien_ban_kiem_ke_vthh_can_dieu_chinh
from . import bao_cao_bien_ban_kiem_ke_thanh_vien_tham_gia
from . import bao_cao_gia_thanh_tong_hop_nhap_xuat_kho_theo_doi_tuong
from . import bao_cao_gia_thanh_bang_ke_phieu_nhap_phieu_xuat_theo_doi_tuong
from . import bao_cao_bang_tinh_khau_hao_tscd
from . import bao_cao_bang_tinh_khau_hao_tscd_chi_tiet
from . import bao_cao_gia_thanh_bang_tong_hop_chi_phi
from . import bao_cao_dieu_chinh_cong_cu_dung_cu
from . import bao_cao_dieu_chinh_cong_cu_dung_cu_chi_tiet
from . import bao_cao_chung_tu_ghi_tang_ccdc
from . import bao_cao_chung_tu_ghi_tang_ccdc_chi_tiet
from . import bao_cao_gia_thanh_tong_hop_lai_lo_theo_cong_trinh
from . import bao_cao_gia_thanh_chi_tiet_lai_lo_theo_cong_trinh
from . import bao_cao_chi_tiet_lai_lo_theo_don_hang
from . import bao_cao_chi_tiet_lai_lo_theo_hop_dong
from . import bao_cao_tong_hop_lai_lo_theo_hop_dong
from . import bao_cao_phieu_xuat_kho_ban_hang_a5
from . import bao_cao_phieu_xuat_kho_ban_hang_a5_chi_tiet
from . import bao_cao_phieu_xuat_kho_ban_hang_a5_doc
from . import bao_cao_phieu_xuat_kho_ban_hang_a5_doc_chi_tiet
from . import bao_cao_uy_nhiem_chi_vietcombank
from . import bao_cao_uy_nhiem_chi_vietcombank_chi_tiet
from . import bao_cao_don_dat_hang_tu_chung_tu_ban_hang
from . import bao_cao_don_dat_hang_tu_chung_tu_ban_hang_chi_tiet
from . import bao_cao_phieu_xuat_kho_tong_hop
from . import bao_cao_phieu_xuat_kho_tong_hop_chi_tiet