# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from . import tien_ich_danh_lai_so_chung_tu
from . import tien_ich_danh_lai_so_chung_tu_chi_tiet
from . import tien_ich_ghi_so_hoac_bo_ghi_so_theo_lo_phan_he
from . import tien_ich_ghi_so_hoac_bo_ghi_so_theo_lo
from . import tien_ich_tim_kiem_chung_tu_ket_qua_tim_kiem
from . import tien_ich_tim_kiem_chung_tu_cac_dieu_kien_da_chon
from . import tien_ich_tim_kiem_chung_tu
# from . import tien_ich_bao_cao
from . import tien_ich_kiem_tra_doi_chieu_chung_tu_so_sach
from . import tien_ich_bao_tri_du_lieu
from . import tien_ich_bao_cao_tai_chinh_chi_tiet
from . import tien_ich_bao_cao_tai_chinh_chi_tiet_mac_dinh
from . import tien_ich_thuc_hien_nghia_vu_doi_voi_nha_nuoc_chi_tiet
from . import tien_ich_thuc_hien_nghia_vu_doi_voi_nha_nuoc_chi_tiet_mac_dinh
from . import tien_ich_thuyet_minh_bao_cao_tai_chinh_chi_tiet
from . import tien_ich_thuyet_minh_bao_cao_tai_chinh_chi_tiet_mac_dinh
from . import tien_ich_thiet_lap_bao_cao_tai_chinh
from . import tien_ich_kiem_tra_cong_thuc_bi_thiet_lap_trung_lap_chi_tiet
from . import tien_ich_kiem_tra_cong_thuc_thiet_lap_trung_lap
from . import tien_ich_xay_dung_cong_thuc_loai_chi_tieu_chi_tiet
from . import tien_ich_xay_dung_cong_thuc_loai_chi_tieu_tong_hop
from . import tien_ich_tinh_hinh_thnvdvnn_pnkt_loai_chi_tieu_chi_tiet
from . import tien_ich_tinh_hinh_thnvdvnn_pnkt_loai_chi_tieu_tong_hop
from . import tien_ich_tinh_hinh_thnvdvnn_pntk_loai_chi_tieu_chi_tiet
from . import tien_ich_tinh_hinh_thnvdvnn_pntk_loai_chi_tieu_tong_hop
from . import tien_ich_tinh_hinh_thnvdvnn_dntk_loai_chi_tieu_chi_tiet
from . import tien_ich_tinh_hinh_thnvdvnn_dntk_loai_chi_tieu_tong_hop
from . import tien_ich_xay_dung_cong_thuc_mac_dinh
from . import tien_ich_xay_dung_cong_thuc_loai_chi_tieu_chi_tiet_mac_dinh

from . import tien_ich_tinh_hinh_thnvdvnn_dntk_loai_chi_tieu_chi_tiet_mac_dinh
from . import tien_ich_tinh_hinh_thnvdvnn_dntk_loai_chi_tieu_tong_hop_mac_dinh
from . import tien_ich_tinh_hinh_thnvdvnn_pnkt_loai_chi_tieu_chi_tiet_mac_dinh
from . import tien_ich_tinh_hinh_thnvdvnn_pnkt_loai_chi_tieu_tong_hop_mac_dinh
from . import tien_ich_tinh_hinh_thnvdvnn_pntk_loai_chi_tieu_chi_tiet_mac_dinh
from . import tien_ich_tinh_hinh_thnvdvnn_pntk_loai_chi_tieu_tong_hop_mac_dinh

from . import tong_hop_lap_bao_cao_tai_chinh
from . import tong_hop_lap_bao_cao_tai_chinh_chi_tiet
from . import tong_hop_bao_cao_tai_chinh
from . import tong_hop_bao_cao_tai_chinh_chi_tiet_b01_dn
from . import tong_hop_bao_cao_tai_chinh_chi_tiet_b02_dn
from . import tong_hop_bao_cao_tai_chinh_chi_tiet_b03_dn
from . import tong_hop_bao_cao_tai_chinh_chi_tiet_b03_dn_gt
from . import tong_hop_bctc_kiem_tra_bang_ke_toan_khong_can_form
from . import tong_hop_bctc_kiem_tra_ke_toan_ko_can_chi_tiet_chi_tieu_form
from . import tong_hop_bctc_kiem_tra_ke_toan_ko_can_chi_tiet_lai_lo_form
from . import tong_hop_bctc_kiem_tra_ke_toan_ko_can_chi_tiet_tk_form
from . import tong_hop_bctc_chon_nghiep_vu_cho_cac_chung_tu_form
from . import tong_hop_bctc_chon_nghiep_vu_cho_cac_chung_tu_chi_tiet_form
from . import tong_hop_bctc_chon_lai_hoat_dong_lctt_form
from . import tong_hop_bctc_chon_lai_hoat_dong_lctt_chi_tiet_form
from . import tong_hop_bctc_chon_nghiep_vu_va_hoat_dong_lctt_form
from . import tong_hop_bctc_chon_nv_va_hd_lctt_chi_tiet_dieu_chinh_form
from . import tong_hop_bctc_chon_nv_va_hd_lctt_chi_tiet_ko_theo_dt_form
from . import tong_hop_bctc_chon_nv_va_hd_lctt_chi_tiet_theo_dt_form
from . import tong_hop_bctc_chon_nv_va_hd_lctt_chi_tiet_phat_sinh_form
from . import tong_hop_bctc_them_phu_luc_form
from . import tien_ich_xay_dung_cong_thuc_tmbctc_loai_chi_tieu_tong_hop
from . import tien_ich_xay_dung_cong_thuc_tmbctc_loai_chi_tieu_chi_tiet
from . import tien_ich_xay_dung_cong_thuc_tmbctc_tong_hop_mac_dinh
from . import tien_ich_xay_dung_cong_thuc_tmbctc_loai_chi_tieu_chi_tiet_mac_dinh
from . import tien_ich_cau_hinh_lai_lo_cho_ct_hd_dh
from . import tien_ich_cau_hinh_lai_lo_cho_ct_hd_dh_cong_thuc
