# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Mua hàng',
    'version': '1.0',
    'sequence': 0,
    'summary': 'Quản lý mua hàng',
    'depends': [		
        'danh_muc',
        'account_ex',
        'stock_ex',
    ],
    'data': [
		# 'views/purchase_ex_chon_chung_tu_mua_hang_form_view.xml',
		# 'views/purchase_ex_phan_bo_chi_phi_view.xml',
		'views/purchase_ex_lap_tu_chung_tu_ban_hang_form_view.xml',
		'views/purchase_ex_chon_tu_lenh_san_xuat_form_view.xml',
		'views/purchase_ex_lap_tu_don_mua_hang_form_view.xml',
		# 'views/purchase_ex_bo_doi_tru_view.xml',
		'views/purchase_ex_doi_tru_chung_tu_nhieu_doi_tuong_view.xml',
		# 'templates/purchase_ex_don_mua_hang_template.xml',
		'views/purchase_ex_hop_dong_mua_hang_view.xml',
		'views/purchase_ex_phan_bo_chiet_khau_theo_hoa_don_view.xml',
		'views/purchase_ex_chon_chung_tu_chi_phi_view.xml',
		'views/purchase_ex_chung_tu_bu_tru_cong_no_ket_qua_view.xml',
		# 'views/purchase_ex_chung_tu_bu_tru_cong_no_ket_qua_ctcn_view.xml',
		# 'views/purchase_ex_chung_tru_bu_tru_cong_no_ket_qua_hach_toan_view.xml',
		'templates/purchase_ex_nhan_hoa_don_mua_hang_hoa_template.xml',
		# 'templates/purchase_ex_tra_lai_mua_hang_mau_02vt_template.xml',
		# 'templates/purchase_ex_tra_lai_mua_hang_mau_02vt_a5_template.xml',
		# 'templates/purchase_ex_tra_lai_mua_hang_mau_phieu_thu_01_tt_template.xml',
		# 'templates/purchase_ex_tra_lai_mua_hang_mau_phieu_thu_01_tt_2lien_template.xml',
		# 'templates/purchase_ex_tra_lai_mua_hang_mau_phieu_thu_01_tt_maua5_template.xml',
		# 'templates/purchase_ex_tra_lai_mua_hang_ctkt_template.xml',
		# 'templates/purchase_ex_giam_gia_mua_hang_mau_phieu_thu_01_tt_template.xml',
		# 'templates/purchase_ex_giam_gia_mua_hang_mau_phieu_thu_01_tt_2lien_template.xml',
		# 'templates/purchase_ex_giam_gia_mua_hang_mau_phieu_thu_01_tt_maua5_template.xml', 
		# 'views/purchase_ex_nhan_hoa_don_mua_hang_hoa_chi_tiet_view.xml',
		# 'views/purchase_ex_nhan_hoa_don_chi_tiet_view.xml',
		'views/purchase_ex_nhan_hoa_don_mua_hang_hoa_view.xml',
		'views/purchase_ex_nhan_hoa_don_view.xml',
		# 'templates/purchase_ex_giam_gia_hang_mua_template.xml',
		'views/purchase_ex_giam_gia_hang_mua_view.xml',
		'views/purchase_ex_bu_tru_cong_no_view.xml',
        'views/purchase_ex_chung_tu_mua_dich_vu_view.xml',
		'views/purchase_ex_tra_lai_hang_mua_view.xml',
		'views/purchase_ex_doi_tru_chung_tu_view.xml',
        'views/purchase_ex_chung_tu_mua_hang_hoa_view.xml',
        'views/purchase_ex_chung_tu_mua_hang_chi_tiet_view.xml',
        'views/purchase_ex_tra_tien_nha_cung_cap_view.xml',
        # 'templates/purchase_ex_01_vt_phieu_nhap_kho_template.xml',
        # 'templates/purchase_ex_02_tt_phieu_chi_template.xml',
        'templates/purchase_ex_templates.xml',
        # 'templates/purchase_ex_phieu_chi_uy_nhiem_chi_mb_template.xml',	
        # 'templates/purchase_ex_phieu_chi_uy_nhiem_chi_agribank_template.xml',	
        'templates/purchase_ex_phieu_chi_uy_nhiem_chi_bidv_template.xml',	
        'templates/purchase_ex_phieu_chi_uy_nhiem_chi_pvcombank_template.xml',	
        # 'templates/purchase_ex_phieu_chi_uy_nhiem_chi_techcombank_template.xml',	
        # 'templates/purchase_ex_phieu_chi_uy_nhiem_chi_vietcombank_template.xml',	
        # 'templates/purchase_ex_phieu_chi_uy_nhiem_chi_viettinbank_template.xml',	
        'templates/purchase_ex_phieu_chi_uy_nhiem_chi_shb_template.xml',	
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': [],
}
