# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from . import danh_muc_co_cau_to_chuc
from . import res_users
from . import danh_muc_khoan_muc_cp
from . import danh_muc_ngan_hang
from . import danh_muc_loai_tai_san_co_dinh
from . import danh_muc_loai_cong_cu_dung_cu
from . import danh_muc_hop_dong_ban
from . import danh_muc_hop_dong_mua
from . import danh_muc_ky_tinh_gia_thanh
from . import danh_muc_thanh_pham
from . import danh_muc_loai_tien
from . import danh_muc_nhom_hhdv
from . import danh_muc_mau_so_hd
from . import danh_muc_loai_chung_tu
from . import danh_muc_doi_tuong_tap_hop_chi_phi
from . import danh_muc_cong_trinh
from . import danh_muc_tai_khoan_ket_chuyen
from . import danh_muc_import_dau_ky
from . import danh_muc_loai_cong_trinh
from . import danh_muc_bieu_thue_tai_nguyen
from . import danh_muc_bieu_thue_tieu_thu_dac_biet
from . import danh_muc_tai_khoan_ngam_dinh
from . import danh_muc_tai_khoan_ngam_dinh_chi_tiet
from . import danh_muc_doi_tuong_phan_bo
from . import danh_muc_don_vi_tinh
from . import danh_muc_kho
from . import danh_muc_so_kho
from . import danh_muc_vat_tu_hang_hoa
from . import danh_muc_vat_tu_hang_hoa_chiet_khau
from . import danh_muc_vat_tu_hang_hoa_don_vi_chuyen_doi
from . import danh_muc_vat_tu_hang_hoa_ma_quy_cach
from . import danh_muc_vat_tu_hang_hoa_dac_tinh_hinh_anh
from . import danh_muc_doi_tuong_chi_tiet
from . import danh_muc_doi_tuong
from . import danh_muc_doi_tuong_dia_diem_giao_hang
from . import danh_muc_nhom_khach_hang_nha_cung_cap
from . import danh_muc_tai_khoan_ngan_hang
from . import danh_muc_dieu_khoan_thanh_toan
from . import danh_muc_ma_thong_ke
from . import danh_muc_menh_gia_loai_tien
from . import danh_muc_lenh_san_xuat
from . import danh_muc_chi_tiet_doi_tuong_tong_hop_chi_phi
from . import danh_muc_chi_tiet_doi_tuong_tinh_gia_thanh
from . import danh_muc_so_cai
from . import danh_muc_so_mua_hang
from . import danh_muc_so_ban_hang
from . import danh_muc_so_ccdc
from . import danh_muc_he_thong_tai_khoan
from . import danh_muc_dinh_khoan_tu_dong
from . import danh_muc_nhom_vat_tu_hang_hoa_dich_vu
from . import danh_muc_so_tscd
from . import danh_muc_so_cong_no
from . import danh_muc_so_thue
from . import danh_muc_thue_suat_gia_tri_gia_tang
from . import danh_muc_ky_hieu_cham_cong_tien_luong
from . import danh_muc_bieu_tinh_thue_thu_nhap_tien_luong
from . import danh_muc_vat_tu_hang_hoa_chi_tiet_dinh_muc_nguyen_vat_lieu
from . import danh_muc_reftype
from . import danh_muc_nhom_loai_chung_tu
from . import danh_muc_vthh_don_gia_mua_gan_nhat
from . import danh_muc_vthh_don_gia_mua_co_dinh
from . import danh_muc_nhom_chung_tu
from . import danh_muc_dsct_phat_sinh_ma_quy_cach_chi_tiet
from . import danh_muc_dsct_phat_sinh_ma_quy_cach_form
from . import danh_muc_hanh_chinh
