# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Kế toán',
    'version': '1.0',
    'sequence': 0,
    'summary': 'Quản lý Quỹ và Ngân hàng',
    'depends': [
        'base_setup',
        'mail',
        'resource',
        'web',
        'danh_muc',
		
    ],
    'data': [
		'views/account_ex_chi_phi_do_dang_master_view.xml',
		'views/account_ex_ton_kho_vat_tu_hang_hoa_master_view.xml',
		'views/account_ex_doi_chieu_ngan_hang_view.xml',
		'views/account_ex_chon_chung_tu_xuat_kho_mua_hang_view.xml',
		# 'templates/phieu_chi_uy_nhiem_chi_vietcombank_template.xml',
		# 'templates/phieu_chi_uy_nhiem_chi_techcombank_template.xml',
		# 'templates/phieu_chi_uy_nhiem_chi_viettinbank_template.xml',
		# 'templates/phieu_chi_uy_nhiem_chi_mb_template.xml',
		# 'templates/phieu_chi_uy_nhiem_chi_pvcombank_template.xml',
		# 'templates/phieu_chi_uy_nhiem_chi_agribank_template.xml',
		# 'templates/phieu_chi_uy_nhiem_chi_shb_template.xml',
		# 'templates/account_ex_02_TT_phieu_chi_day_du_template.xml',
		# 'templates/account_ex_phieu_chi_uy_nhiem_chi_bidv_template.xml',
		# 'templates/account_ex_02_TT_phieu_chi_a5_template.xml',
		# 'templates/account_ex_02_TT_phieu_chi_2_lien_template.xml',
		# 'templates/account_ex_01_TT_phieu_thu_day_du_template.xml',
		# 'templates/account_ex_01_TT_phieu_thu_a5_template.xml',
		# 'templates/account_ex_01_TT_phieu_thu_2_lien_template.xml',
		# 'templates/phieu_chi_giay_bao_no_template.xml',
		# 'templates/phieu_thu_giay_bao_co_template.xml',
		# 'templates/account_ex_02_TT_phieu_chi_template.xml',
		# 'templates/account_ex_01_TT_phieu_thu_template.xml',
		'templates/account_ex_templates.xml',

		# 'templates/account_ex_don_dat_hang_template.xml',

		'views/account_ex_thu_tien_gui_tu_khach_hang_view.xml',
		'views/account_ex_chon_chung_tu_form_view.xml',
		'views/account_ex_quy_phieu_chi_tien_view.xml',
		'views/account_ex_quy_phieu_thu_tien_view.xml',
		'views/account_ex_tra_tien_nha_cung_cap.xml',
		'views/account_ex_chi_tiet_theo_hoa_don_khach_hang_view.xml',
		'views/account_ex_chi_tiet_theo_nv_dv_ct_dh_hd_view.xml',
		'views/account_ex_nhap_chi_tiet_cong_no_nhan_vien_view.xml',
		'views/account_ex_chi_tiet_theo_hoa_don_view.xml',
		'views/account_ex_nhap_chi_tiet_cong_no_khach_hang_view.xml',
		'views/account_ex_so_du_tai_khoan_chi_tiet_view.xml',
		'views/account_ex_ton_kho_vat_tu_hang_hoa_view.xml',
		'views/account_ex_chi_phi_do_dang_view.xml',
		'views/account_ex_cong_no_nhan_vien_view.xml',
		'views/account_ex_cong_no_khach_hang_view.xml',
		'views/account_ex_so_du_tk_ngan_hang_view.xml',
		'views/account_ex_so_du_tai_khoan_view.xml',
		'views/account_ex_nhap_so_du_ban_dau_view.xml',
		# 'views/account_ex_ket_chuyen_lai_lo_detail_view.xml',
		# 'views/account_ex_ket_chuyen_lai_lo_master_view.xml',
		# 'views/account_ex_tam_ung_hoa_don_view.xml',
		# 'views/account_ex_tam_ung_hach_toan_view.xml',
		# 'views/account_ex_chung_tu_quyet_toan_tam_ung_view.xml',
		# 'views/account_ex_chung_tu_nghiep_vu_khac_hach_toan_view.xml',
		# 'views/account_ex_chung_tu_nghiep_vu_khac_view.xml',
		'views/account_ex_chuyen_tien_noi_bo_view.xml',
        'views/account_ex_ngan_hang_phieu_chi_tien_view.xml',
        'views/account_ex_ngan_hang_phieu_thu_tien_view.xml',
        'views/account_ex_don_mua_hang_view.xml',

		'views/account_ex_don_dat_hang.xml',
		'views/account_ex_don_dat_hang_xem_sl_ton_chua_dat_hang_form_view.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': [],
}
