# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from . import sale_ex_chung_tu_ban_hang
from . import sale_ex_chung_tu_ban_hang_chi_tiet
from . import sale_ex_hoa_don_ban_hang
# from . import sale_ex_hoa_don_dien_tu
from . import sale_ex_hoa_don_ban_hang_chi_tiet
from . import sale_ex_doi_tru_chung_tu_thanh_toan
from . import sale_ex_doi_tru_chung_tu_cong_no
from . import sale_ex_doi_tru_chung_tu
from . import sale_ex_thu_tien_khach_hang
from . import sale_ex_thu_tien_khach_hang_chi_tiet
from . import sale_ex_giam_gia_hang_ban
from . import sale_ex_giam_gia_hang_ban_chi_tiet
from . import sale_ex_tra_lai_hang_ban
from . import sale_ex_tra_lai_hang_ban_chi_tiet
from . import sale_ex_templates
from . import sale_ex_bao_gia
from . import sale_ex_bao_gia_chi_tiet
from . import sale_ex_phan_bo_chiet_khau_theo_tong_gia_tri_hd_form
from . import sale_ex_phan_bo_chiet_khau_theo_tong_gia_tri_hd_chi_tiet
from . import sale_ex_tinh_gia_ban
from . import sale_ex_tinh_gia_ban_chi_tiet
from . import sale_ex_doi_tru_chung_tu_chi_tiet_thanh_toan
from . import sale_ex_doi_tru_chung_tu_chi_tiet_cong_no
from . import sale_ex_doi_tru_chung_tu_nhieu_doi_tuong
from . import sale_ex_doi_tru_chung_tu_nhieu_doi_tuong_chi_tiet
from . import sale_ex_bo_doi_tru
from . import sale_ex_bo_doi_tru_chi_tiet
from . import sale_ex_bu_tru_cong_no
from . import sale_ex_bu_tru_cong_no_chung_tu_phai_thu
from . import sale_ex_bu_tru_cong_no_chung_tu_phai_tra
from . import sale_ex_doi_tru_chi_tiet
from . import sale_ex_hop_dong_ban
from . import sale_ex_hop_dong_ban_chi_tiet_ban_hang
from . import sale_ex_hop_dong_ban_chi_tiet_du_kien_chi
from . import sale_ex_hop_dong_ban_chi_tiet_ghi_nhan_doanh_so
from . import sale_ex_hop_dong_ban_chi_tiet_hang_hoa_dich_vu
from . import sale_ex_hop_dong_ban_chi_tiet_lien_he
from . import sale_ex_hop_dong_ban_chi_tiet_thuc_thi
from . import sale_ex_hop_dong_ban_chi_tiet_thuc_thu
from . import account_ex_don_mua_hang_chi_tiet_ex
from . import sale_ex_hop_dong_ban_chon_chung_tu_chi_form
from . import sale_ex_hop_dong_ban_chon_chung_tu_chi_chi_tiet_form
from . import sale_ex_hop_dong_ban_chon_chung_tu_thu_form
from . import sale_ex_hop_dong_ban_chon_chung_tu_thu_chi_tiet_form
from . import hop_dong_ban_report
from . import account_ex_phieu_thu_chi_tiet
# from . import account_ex_phieu_thu_chi_tiet_don_dat_hang
from . import danh_muc_so_ban_hang
from . import account_ex_don_dat_hang_bao_gia
from . import stock_ex_nhap_xuat_kho
from . import account_ex_phieu_thu_chi
from . import purchase_ex_chung_tu_mua_dich_vu_chi_tiet
from . import purchase_ex_tra_lai_hang_mua
from . import purchase_ex_tra_lai_hang_mua_chi_tiet
from . import purchase_ex_giam_gia_hang_mua_chi_tiet
from . import purchase_ex_hoa_don_mua_hang
from . import danh_muc_so_kho
from . import sale_ex_chung_tu_ban_hang_excel
