# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Giá thành',
    'version': '1.0',
    'sequence': 0,
    'summary': 'Module mẫu',
    'depends': [
        'base_setup',
        'mail',
        'resource',
        'web',
        'danh_muc',
        'sale_ex',
        'account_ex',
    ],
    'data': [
		'templates/gia_thanh_nghiem_thu_chung_tu_ke_toan_template.xml',
		'views/gia_thanh_bang_tap_hop_chi_phi_theo_khoan_muc_san_xuat_lien_tuc_gian_don_view.xml',
		'views/gia_thanh_bang_tap_hop_chi_phi_theo_khoan_muc_san_xuat_lien_tuc_he_so_ty_le_view.xml',
		'views/gia_thanh_tap_hop_khoan_giam_gia_thanh_san_xuat_lien_tuc_gian_don_view.xml',
		'views/gia_thanh_tap_hop_khoan_giam_gia_thanh_san_xuat_lien_tuc_he_so_ty_le_view.xml',
		'views/gia_thanh_chon_doi_tuong_can_tap_hop_chi_phi_form_view.xml',
		'views/gia_thanh_dinh_muc_nguyen_vat_lieu_cong_trinh_view.xml',
		'views/gia_thanh_tap_hop_chi_phi_truc_tiep_hop_dong_view.xml',
		'views/gia_thanh_khai_bao_dinh_muc_phan_bo_chi_phi_theo_doi_tuong_thcp_form_view.xml',
		'views/gia_thanh_khai_bao_dinh_muc_gia_thanh_thanh_pham_form_view.xml',
		'views/gia_thanh_chon_ky_tinh_gia_thanh_ket_chuyen_form_view.xml',
		'views/gia_thanh_danh_sach_ket_chuyen_chi_phi_view.xml',
		'views/gia_thanh_ket_chuyen_chi_phi_san_xuat_lien_tuc_he_so_ty_le_view.xml',
		'views/gia_thanh_ket_chuyen_chi_phi_san_xuat_lien_tuc_gian_don_view.xml',
		'views/gia_thanh_bang_tap_hop_chi_phi_theo_yeu_to_san_xuat_lien_tuc_gian_don_view.xml',
		'views/gia_thanh_bang_tap_hop_chi_phi_theo_yeu_to_san_xuat_lien_tuc_he_so_ty_le_view.xml',
		'views/gia_thanh_nghiem_thu_cong_trinh_view.xml',
		'views/gia_thanh_phan_bo_chi_phi_chung_cong_trinh_view.xml',
		'views/gia_thanh_ky_tinh_gia_thanh_san_xuat_lien_tuc_gian_don_view.xml',
		'views/gia_thanh_ket_chuyen_chi_phi_cong_trinh_view.xml',
		'views/gia_thanh_tap_hop_chi_phi_truc_tiep_san_xuat_lien_tuc_gian_don_view.xml',
		'views/gia_thanh_tap_hop_chi_phi_truc_tiep_san_xuat_lien_tuc_he_so_ty_le_view.xml',
		'views/gia_thanh_tinh_gia_thanh_san_xuat_lien_tuc_gian_don_view.xml',
		'views/gia_thanh_tinh_gia_thanh_san_xuat_lien_tuc_he_so_ty_le_view.xml',
		'views/gia_thanh_ky_tinh_gia_thanh_san_xuat_lien_tuc_gian_don_view.xml',
		'views/gia_thanh_ky_tinh_gia_thanh_san_xuat_lien_tuc_he_so_ty_le_view.xml',
		'views/gia_thanh_ky_tinh_gia_thanh_cong_trinh_view.xml',
		'views/gia_thanh_ky_tinh_gia_thanh_don_hang_view.xml',
		'views/gia_thanh_ky_tinh_gia_thanh_hop_dong_view.xml',
		'views/gia_thanh_bang_tap_hop_chi_phi_theo_yeu_to_cong_trinh_view.xml',
		'views/gia_thanh_bang_tap_hop_chi_phi_theo_khoan_muc_cong_trinh_view.xml',
		'views/gia_thanh_tap_hop_chi_phi_truc_tiep_cong_trinh_view.xml',
		'views/gia_thanh_tap_hop_khoan_giam_gia_thanh_cong_trinh_view.xml',
		'views/gia_thanh_tap_hop_chi_phi_truc_tiep_don_hang_view.xml',
		'views/gia_thanh_tap_hop_khoan_giam_gia_thanh_don_hang_view.xml',
		'views/gia_thanh_phan_bo_chi_phi_chung_don_hang_view.xml',
		'views/gia_thanh_ket_chuyen_chi_phi_don_hang_view.xml',
		'views/gia_thanh_chon_ky_tinh_gia_thanh_nghiem_thu_tham_so_form_view.xml',
		# 'views/gia_thanh_chon_ky_tinh_gia_thanh_cong_trinh_form_view.xml',
		# 'views/gia_thanh_chon_ky_tinh_gia_thanh_don_hang_form_view.xml',
		'views/gia_thanh_nghiem_thu_don_hang_view.xml',
		'views/gia_thanh_bang_tap_hop_chi_phi_theo_yeu_to_don_hang_view.xml',
		'views/gia_thanh_bang_tap_hop_chi_phi_theo_khoan_muc_don_hang_view.xml',
		'views/gia_thanh_tap_hop_khoan_giam_gia_thanh_hop_dong_view.xml',
		'views/gia_thanh_phan_bo_chi_phi_chung_hop_dong_view.xml',
		'views/gia_thanh_ket_chuyen_chi_phi_hop_dong_view.xml',
		# 'views/gia_thanh_chon_ky_tinh_gia_thanh_hop_dong_form_view.xml',
		'views/gia_thanh_nghiem_thu_hop_dong_view.xml',
		'views/gia_thanh_bang_tap_hop_chi_phi_theo_yeu_to_hop_dong_view.xml',
		'views/gia_thanh_bang_tap_hop_chi_phi_theo_khoan_muc_hop_dong_view.xml',
		'views/gia_thanh_khai_bao_dinh_muc_phan_bo_chi_phi_theo_cong_trinh_form_view.xml',
    'templates/gia_thanh_templates.xml',
    'templates/gia_thanh_ket_chuyen_chi_phi_chung_tu_ke_toan_template.xml',
		
		
		
		
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': [],
}
